#pragma once
#define ENABLE_LOCATION_SOURCE 1
#define ENABLE_PROFILING 1
#define CAN_UNWIND_WITH_FRAME_POINTERS 0
#define UNSAFE_DEVELOPER_BUILD 0
#define CAN_UNWIND_WITH_CFI_TABLE 0
#define ENABLE_GDBINIT_WARNING 0
#define ENABLE_LLDBINIT_WARNING 0
